version: '3.8'

services:

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rtp-games-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: zapchat_tur
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: rtp-games-dashboard-super-secret-jwt-key-2024
      JWT_EXPIRES_IN: 7d
      BCRYPT_ROUNDS: 12
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    networks:
      - rtp-network
    volumes:
      - ./backend/prisma:/app/prisma
    command: >
      sh -c "
        export DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable && \
        npx prisma migrate deploy && \
        npx prisma db seed && \
        npm start
      "

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rtp-games-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:3001/api
      VITE_WS_URL: ws://backend:3001/ws
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rtp-network

networks:
  rtp-network:
    driver: bridge

