version: '3.8'

services:
  # Banco de dados PostgreSQL para desenvolvimento
  postgres-dev:
    image: postgres:16
    container_name: rtp-games-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: vigilancia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2412055aa
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - rtp-dev-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 20s
      retries: 10

  # pgAdmin para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: rtp-games-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-dev
    networks:
      - rtp-dev-network

volumes:
  postgres_dev_data:
    driver: local

networks:
  rtp-dev-network:
    driver: bridge

