version: '3.8'

services:
  # Banco de dados MySQL para desenvolvimento
  mysql-dev:
    image: mysql:8.0
    container_name: rtp-games-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rtp_games_dashboard
      MYSQL_USER: rtp_user
      MYSQL_PASSWORD: rtp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - rtp-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rtp-games-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-dev
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql-dev
    networks:
      - rtp-dev-network

volumes:
  mysql_dev_data:
    driver: local

networks:
  rtp-dev-network:
    driver: bridge

