CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "games" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "provider" VARCHAR(255) NOT NULL,
  "category" VARCHAR(255) NOT NULL,
  "minRtp" REAL NOT NULL,
  "maxRtp" REAL NOT NULL,
  "currentRtp" REAL NOT NULL,
  "imageUrl" VARCHAR(255),
  "description" TEXT,
  "isActive" BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "betting_houses" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "apiName" VARCHAR(255) NOT NULL,
  "apiUrl" VARCHAR(255) NOT NULL,
  "updateInterval" INTEGER NOT NULL,
  "currency" VARCHAR(32) NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "rtp_history" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "gameId" INTEGER NOT NULL REFERENCES "games"("id") ON DELETE CASCADE,
  "rtpValue" REAL NOT NULL,
  "timestamp" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "notes" TEXT
);
